### PR TITLE
Restructuring billing section

### LINKED ISSUE #1117: [Bug]: Update recommended testnet LINK amount for VRF tutorial
### Describe the bug

The [Get a Random Number](https://docs.chain.link/vrf/v2/subscription/examples/get-a-random-number) (Subscription) tutorial recommends funding the subscription initially with 2 LINK - just enough to cover the request. The tutorial does not mention that the subscription balance must meet or exceed the "Max Cost" for the request to go through successfully.

When following the tutorial today, I found the Max Cost was over 10.5 LINK, and then the transaction settled successfully for 2.76 LINK.

### To Reproduce

1. Fund your subscription initially with 2 LINK, as the tutorial recommends
2. Request randomness from Remix UI, as instructed in the tutorial
3. In the Subscription UI, see that your request is pending because the subscription balance needs to meet or exceed the Max Cost

Screen Shot 2023-01-17 at 12 25 19 PM

### URLs

https://docs.chain.link/vrf/v2/subscription/examples/get-a-random-number

### Expected behavior

The tutorial should recommend initial subscription funding of 12 LINK to cover the max cost, and also explain that the cost of one request after fulfillment will be around 3 LINK.

It should also link to the relevant troubleshooting section for the Subscription UI that explains pending requests in more detail.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by thedriftofwords**
## Description

- Create one cohesive billing page (Estimating Costs) that combines info for subscription and direct funding costs, using tabbed sections
- Add cost breakdown examples for subscription and direct funding (extends [this Stack Overflow answer](https://stackoverflow.com/a/72267377))
- Expand explanation of minimum subscription balance, creating a clearly labeled section for it, and linking to it from other docs
- Restructuring index pages for subscription and direct funding
- Fixing links
- https://github.com/smartcontractkit/documentation/pull/1135/commits/3e88045f3e6e96b8f9869a3e121db8b7cb0c5720 resolves #1117

### CODE REVIEW

**Review by dwightjl — APPROVED** [review]

File: src/config/sidebar.ts [hunk 1]
```diff
@@ -270,6 +270,8 @@ export const SIDEBAR = {
           title: "LINK Token Contracts",
           url: "resources/link-token-contracts?parent=dataFeeds",
         },
+        { title: "Getting Help", url: "resources/getting-help" },
+        { title: "Hackathon Resources", url: "resources/hackathon-resources?parent=dataFeeds" },
```
Comment (dwightjl) [inline src/config/sidebar.ts:274]:
```suggestion
```

Remove these duplicates.

File: src/pages/vrf/v2/estimating-costs.mdx [hunk 2]
```diff
@@ -0,0 +1,257 @@
...
+<Fragment slot="panel.2">
+
+A LINK premium is then added to the total gas cost. The premium is divided in two parts:
+
+- Wrapper premium: The premium percentage. You can find the percentage for your network in the [Supported networks](/vrf/v2/direct-funding/supported-networks/#configurations) page.
+- Coordinator premium: A flat fee. This premium is defined in the `fulfillmentFlatFeeLinkPPMTier1` parameter in millionths of LINK. You can find the flat fee of the coordinator for your network in the [Supported networks](/vrf/v2/direct-funding/supported-networks/#configurations) page.
+
+```
+(Coordinator premium
+  + (total gas cost * Wrapper premium)) = total request cost
```
Comment (dwightjl) [inline src/pages/vrf/v2/estimating-costs.mdx:128]:
```suggestion
(Coordinator premium + (total gas cost * Wrapper premium)) = total request cost
```

I think this can be a single line.

**Review by dwightjl — CHANGES_REQUESTED** [review]

**Comment by thedriftofwords** [comment]
TODO: 

- Resolve conflicts
- Update direct funding example again
- Add/update cross-linking (tutorials, Subscription Manager UI page)
- Add max verification gas back to conceptual section

**Review by dwightjl — APPROVED** [review]

**Review by dwightjl — APPROVED** [review]
